name: Pull Request Checks

on:
  pull_request:

permissions:
  contents: write

jobs:
  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - uses: terraform-linters/setup-tflint@v3
        name: Install TFLint
        with:
          tflint_version: v0.44.1
      - name: Install Pre-commit and Checkov
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit checkov
      - name: Run pre-commit
        run: pre-commit run --all-files
      - name: Check for unstaged changes
        run: git diff --exit-code

  pytest:
    name: Pytest
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: eu-west-1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt
      - name: Run pytest
        run: pytest -v --ignore-glob='*test_handler*'
